### ISSUE TITLE
About inference

### ISSUE THREAD

**Issue by liaochuanlin** [oraclefina/GSGNet#1]
Dear author, I have a question. Is the quantitative result obtained in SALICON the result of the verification set?
![image](https://github.com/oraclefina/GSGNet/assets/49152538/18496acb-7b9b-40fc-909f-67d7a1e4c0ad)
![image](https://github.com/oraclefina/GSGNet/assets/49152538/576d906c-ef60-4cc5-8363-d9ce6550cdb5)
Are the test results of MIT300 submitted to https://saliency.tuebingen.ai/? 
I'm sorry I just got in touch with the research in this area, but I don't know much about it.

**Comment by oraclefina** [comment]
For SALICON, you can obtain your testset scores from https://codalab.lisn.upsaclay.fr/competitions/8379.  
For MIT300, submit your predictions to the website and you will receive your results from the website by email.

**Comment by liaochuanlin** [comment]
Thank you for your answer. 
Do you have a download window for TORONTO dataset? I searched for a long time but couldn't find it, and I didn't find the data import code such as TORONTO,MIT300 in my data.py. Can I make it public? 
Thank you again for your reply.

**Comment by oraclefina** [comment]
You just store filenames of images and gt maps as the csv files like the SALICON ones under ./dataset. The data loading process is the same. TORONTO: http://www-sop.inria.fr/members/Neil.Bruce/eyetrackingdata.zip

**Comment by liaochuanlin** [comment]
Dear author, how do you divide the data of TORONTO and PASCAL-S?&nbsp;
I don't have the proportion of them in your paper.&nbsp;
Thank you very much for your reply.





廖川林
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "oraclefina/GSGNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月9日(星期二) 晚上9:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [oraclefina/GSGNet] About inference (Issue #1)





 
You just store filenames of images and gt maps as the csv files like the SALICON ones under ./dataset. The data loading process is the same. TORONTO: http://www-sop.inria.fr/members/Neil.Bruce/eyetrackingdata.zip

**Comment by oraclefina** [comment]
We use the entire datasets of TORONTO and PASCAL-S for evaluation.
Thus, there is no split in those two datasets.

**Comment by liaochuanlin** [comment]
Okay, got it. Thank you for your answer. Thank you very much again.


爩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "oraclefina/GSGNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月11日(星期四) 晚上8:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [oraclefina/GSGNet] About inference (Issue #1)





 
We use the entire datasets of TORONTO and PASCAL-S for evaluation.
 Thus, there is no split in those two datasets.

**Comment by liaochuanlin** [comment]
![image](https://github.com/oraclefina/GSGNet/assets/49152538/9f824e24-56a5-4a02-b4da-3bd60e41dc96)
Dear author, I hope this news will make you feel good. 
Is this code calculated by calling matlab with python? 
If you are willing to share the code that calculates these indicators, my email address is 2651106983@qq.com. 
I'm so sorry to bother you.

**Comment by liaochuanlin** [comment]
Dear author, I am very sorry to bother you: sAUC,IG,NSS in the TORONTO dataset, the result I calculated is very different from that of the paper, and the IG even becomes negative. 
The code for calculating the index is as follows: is there something wrong with this method of calculation? 
Sorry to bother you again!
def infogain(s_map,gt,baseline_map):
	gt = discretize_gt(gt)
	# assuming s_map and baseline_map are normalized
	eps = 2.2204e-16

	s_map = s_map/(np.sum(s_map)*1.0)
	baseline_map = baseline_map/(np.sum(baseline_map)*1.0)

	# for all places where gt=1, calculate info gain
	temp = []
	x,y = np.where(gt==1)
	for i in zip(x,y):
		temp.append(np.log2(eps + s_map[i[0],i[1]]) - np.log2(eps + baseline_map[i[0],i[1]]))

	return np.mean(temp)

**Comment by liaochuanlin** [comment]
Dear author, I am very sorry to bother you: sAUC,IG,NSS in the TORONTO dataset, the result I calculated is very different from that of the paper, and the IG even becomes negative.
The code for calculating the index is as follows: is there something wrong with this method of calculation?
Sorry to bother you again!

def infogain(s_map,gt,baseline_map):
gt = discretize_gt(gt)
# assuming s_map and baseline_map are normalized
eps = 2.2204e-16
s_map = s_map/(np.sum(s_map)*1.0)
baseline_map = baseline_map/(np.sum(baseline_map)*1.0)

# for all places where gt=1, calculate info gain
temp = []
x,y = np.where(gt==1)
for i in zip(x,y):
	temp.append(np.log2(eps + s_map[i[0],i[1]]) - np.log2(eps + baseline_map[i[0],i[1]]))

return np.mean(temp)

**Comment by liaochuanlin** [comment]
Dear author, I am very sorry to bother you: sAUC,IG,NSS in the TORONTO dataset, the result I calculated is very different from that of the paper, and the IG even becomes negative.
The code for calculating the index is as follows: is there something wrong with this method of calculation?
Sorry to bother you again!
def infogain(s_map,gt,baseline_map):
	gt = discretize_gt(gt)
	# assuming s_map and baseline_map are normalized
	eps = 2.2204e-16

	s_map = s_map/(np.sum(s_map)*1.0)
	baseline_map = baseline_map/(np.sum(baseline_map)*1.0)

	# for all places where gt=1, calculate info gain
	temp = []
	x,y = np.where(gt==1)
	for i in zip(x,y):
		temp.append(np.log2(eps + s_map[i[0],i[1]]) - np.log2(eps + baseline_map[i[0],i[1]]))

	return np.mean(temp)

**Comment by liaochuanlin** [comment]
Dear author, I am very sorry to bother you: sAUC,IG,NSS in the TORONTO dataset, the result I calculated is very different from that of the paper, and the IG even becomes negative.
The code for calculating the index is as follows: is there something wrong with this method of calculation?
Sorry to bother you again!
![image](https://github.com/oraclefina/GSGNet/assets/49152538/0f27a678-84d1-4cc5-ad00-0081e067f14c)
![image](https://github.com/oraclefina/GSGNet/assets/49152538/8cd7f04e-a43c-4106-94ff-4406133581e7)

**Comment by oraclefina** [comment]
The python codes of metrics are in loss.py. You can directly use it. I set 352x352 in center_bias for baseline in IG.

**Comment by liaochuanlin** [comment]
![image](https://github.com/oraclefina/GSGNet/assets/49152538/7ee9b9d8-bbb2-485e-94ad-703c8936d219)
![image](https://github.com/oraclefina/GSGNet/assets/49152538/c06d42f8-c5c9-4070-92d5-59d340d907ea)
![image](https://github.com/oraclefina/GSGNet/assets/49152538/787ff4d6-c099-4abf-bf1c-fdec17e444a6)
Dear author, thank you for your reply. According to your hint, I will change the code as shown in the figure, and the final calculated ig is-6.7237. Is there a problem with the implementation of the above code? should the prediction map and truth map be scaled to the same size as baseline (352x352)? 
Look forward to your reply

**Comment by liaochuanlin** [comment]
Dear author, does the PASCAL-S dataset only have element-by-element truth marker graphs?

**Comment by oraclefina** [comment]
I align my predictions with the original resolutions of gt maps before obtaining my prediction PNG FILES , eg. TORONTO is 511,681 and PASCAL-S has different shapes.
The following example is one image evaluation:
```python
#Load Data
pred = cv2.imread(pred_path,cv2.IMREAD_GRAYSCALE) / 255.0
gt = cv2.imread(gt_path,cv2.IMREAD_GRAYSCALE) / 255.0
fix = cv2.imread(FixationMaps_path,cv2.IMREAD_GRAYSCALE)
fix = np.round(fix/255.0)
#To Torch.Tensor with Batch Dim
pred = torch.FloatTensor(pred)[None,:,:]
gt = torch.FloatTensor(gt)[None,:,:]
fix = torch.FloatTensor(fix)[None, :, :]
sp = fix.shape
baseline = torch.FloatTensor(center_bias((sp[1],sp[2])))[None, :, :]
#Compute scores
ig_score = ig(pred, gt, baseline)
```

**Comment by oraclefina** [comment]
If you mean the fixation density maps, you can find under ./algmaps/pascal/humanFix.

**Comment by liaochuanlin** [comment]
The data I downloaded only contains image and mask. Can you share the data set you downloaded?
![image](https://github.com/oraclefina/GSGNet/assets/49152538/134a458a-0bde-401d-8d2d-3e3e449af958)

**Comment by liaochuanlin** [comment]
Dear author, are the gt and fix in this code the same picture?
![image](https://github.com/oraclefina/GSGNet/assets/49152538/ad6307a2-4414-486c-b012-50edbadadda0)

**Comment by oraclefina** [comment]
PASCAL-S: https://academictorrents.com/details/6c49defd6f0e417c039637475cde638d1363037e
gt is the fixation density map, fix is the fixation map with binary values.

**Comment by liaochuanlin** [comment]
Dear author, after I get the picture that is predicted to be aligned with the original resolution of the GT map, the TORONTO evaluation results obtained according to the calculation method in loss are as follows: auc,nss,cc,sim,kl,sauc,ig 0.8578, 1.8485, 0.7518, 0.6201 , 0.5339 , 0.7226, 0.7828 nss and ig there is still a certain gap between the article and the article, and will the aligned baseline still be the 352x352 resolution?

**Comment by liaochuanlin** [comment]
Dear author, are there any precautions for submitting the mit300 test results to saliency@tuebingen.ai this mailbox? 
It has been submitted for a long time without feedback.
![image](https://github.com/oraclefina/GSGNet/assets/49152538/74fc8968-a7f4-45a1-8077-d7007bb5f530)

**Comment by liaochuanlin** [comment]
Dear author, when I replace auc_judd1 = auc_judd (s_map, gt) with auc_judd1 = auc_judd (s_map, fix), the auc result becomes 0.95. the jump is too big.

**Comment by oraclefina** [comment]
What is the model used for inference? 
You can share a Google drive link and so I can evaluate it.
It took a long time for me to get the results from MIT300.
If you give them log density predictions, you will obtain higher scores on some metrics, since their evaluation method optimizes predictions for each metric.

**Comment by liaochuanlin** [comment]
Dear author, I use the model trained by SALICON for reasoning. The weight of the model and the reasoning results are in the following link: https://drive.google.com/drive/folders/1-YnFzOFVhNby5JSE4Bm91vMBztkWFH55?usp=sharing

**Comment by oraclefina** [comment]
I evaluated your predictions. 
The results are normal, NSS=2.1646383, IG=0.9210529.
What did you use for fixation maps?
TORONTO has origfixdata.mat, which contains the ground-truth binary maps for metrics like NSS and IG.
```python
for i,fix in enumerate(fixmat):
    cv2.imwrite("./{}.png".format(i+1),fix * 255)
ig_score = ig(pred, fix, baseline) # It should use fixation maps.
```

**Comment by liaochuanlin** [comment]
I use the fix obtained by discretization of the pictures in / media/test_lcl/GSGNet/dataset/TORONTO/eyetrackingdata/fixdens/Density Maps produced from raw experimental eyetrackingdata. Can you share with me the detailed processing of the origfixdata.mat file and generate the fix code?

**Comment by oraclefina** [comment]
Use scipy.io.loadmat to load the file, and then obtain values by keys.
Make sure that the evaluation files are matched by filenames.

**Comment by liaochuanlin** [comment]
Dear author, what is the acc value you get from the prediction I gave you? 
I have your hint that among the indicators of auc,nss,cc,sim,kl,sauc,ig, only auc has a gap of 0.8655 between auc and the paper. Does the gt here also use fix? Thank you very much for your patience

**Comment by oraclefina** [comment]
Use fix.
Recommend reading "What do different evaluation metrics tell us about saliency models?."

**Comment by liaochuanlin** [comment]
Thank you for your patient reply. I can basically reproduce the results of the TORONTO dataset. Thank you very much!

**Comment by liaochuanlin** [comment]
Dear Author, PASCAL-S:  https://academictorrents.com/details/6c49defd6f0e417c039637475cde638d1363037e cannot be opened Where do you have PASCAL -s dataset. / algmaps/PASCAL/humanFix. Did you? Could you send it to my email address if it is convenient? Thank you so much!!
